example.property= I AM PROD

# DataSource settings: set here your own configurations for the database 
spring.datasource.url = jdbc:postgresql://orders-db:5432/orders
spring.datasource.username = postgres
spring.datasource.password = {cipher}5ed8c7f0a2a17bd1f8b083f7fa35601393c846f2b7adbc0e7018865ed677a654
spring.jpa.show-sql = false
logging.level.root = WARN