example.property= I AM DEV

# DataSource settings: set here your own configurations for the database 
spring.datasource.url = jdbc:postgresql://orders-db:5432/orders
spring.datasource.username = postgres
spring.datasource.password = pass
spring.jpa.show-sql = true