# DataSource settings: set here your own configurations for the database 
spring.datasource.url = jdbc:postgresql://database:5432/ostock_test?sslmode=disable
spring.datasource.username = postgres
# for step 3
spring.datasource.password=pass 
