# DataSource settings: set here your own configurations for the database 
spring.datasource.url = jdbc:postgresql://product-db:5432/products
spring.datasource.username = postgres
spring.datasource.password = pass
spring.jpa.show-sql = true